---

services:
  proxy:
    image: ghcr.io/applicreation/harmony-proxy:v0
    ports:
      - 80:80
  core:
    image: ghcr.io/applicreation/harmony-core:v0
    volumes:
      - ./.harmony/core:/root/.harmony:ro
  example-html:
    image: ghcr.io/applicreation/harmony-module-example-html:v0
  example-node:
    image: ghcr.io/applicreation/harmony-module-example-node:v0
  example-php:
    image: ghcr.io/applicreation/harmony-module-example-php:v0
  catalog:
    image: ghcr.io/applicreation/harmony-module-catalog:v0
    env_file:
      - ./.harmony/catalog/.env
    volumes:
      - ./.harmony/catalog:/root/.harmony:ro
  docs:
    image: ghcr.io/applicreation/harmony-module-docs:v0
    env_file:
      - ./.harmony/docs/.env
    volumes:
      - ./.harmony/docs:/root/.harmony:ro
