---

services:
  proxy:
    image: ghcr.io/applicreation/harmony-proxy:latest
    ports:
      - 80:80
  core:
    image: ghcr.io/applicreation/harmony-core:latest
    volumes:
      - ./.harmony/core:/root/.harmony:ro
  example:
    image: ghcr.io/applicreation/harmony-module-example
  catalog:
    image: ghcr.io/applicreation/harmony-module-catalog
