---

services:
  proxy:
    image: ghcr.io/applicreation/harmony-proxy:v0
    ports:
      - 80:80
  core:
    image: ghcr.io/applicreation/harmony-core:v0
    restart: on-failure
    env_file:
      - ./.harmony/core/.env
      - ./.harmony/core/main.env
    volumes:
      - ./.harmony/core:/root/.harmony:ro
  catalog:
    image: ghcr.io/applicreation/harmony-module-catalog:v0
    restart: on-failure
    env_file:
      - ./.harmony/catalog/.env
    volumes:
      - ./.harmony/catalog:/root/.harmony:ro
  docs:
    image: ghcr.io/applicreation/harmony-module-docs:v0
    restart: on-failure
    env_file:
      - ./.harmony/docs/.env
    volumes:
      - ./.harmony/docs:/root/.harmony:ro
