---

auth:
  clients:
    google:
      client_id: ${{GOOGLE_CLIENT_ID}}
      client_secret: ${{GOOGLE_CLIENT_SECRET}}
      redirect_host: ${{GOOGLE_REDIRECT_HOST}}
modules:
  - id: catalog
  - id: docs
