---

base_url: ${{BASE_URL}}
auth:
  token_secret: ${{AUTH_TOKEN_SECRET}}
  token_ttl: ${{AUTH_TOKEN_TTL}}
  google:
    client_id: ${{AUTH_GOOGLE_CLIENT_ID}}
github:
  token: ${{GITHUB_TOKEN}}
modules:
  - id: catalog
  - id: docs
