---

base_url: ${{BASE_URL}}
auth:
  clients:
    google:
      client_id: ${{GOOGLE_CLIENT_ID}}
      client_secret: ${{GOOGLE_CLIENT_SECRET}}
github:
  token: ${{GITHUB_TOKEN}}
modules:
  - id: catalog
  - id: docs
