---

auth:
  auth0:
    domain: harmony-dev.eu.auth0.com
    client_id: peNrbX6FNFKezAEkjejd4bIvGOpXVh2d
modules:
  - id: example-html
  - id: example-node
  - id: example-php
  - id: catalog
  - id: docs
